name: ReadAPI CI

on:
  push:
    branches:
      - development
      - apis
      
jobs:  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test_read
      env:
        CI: true

    - name: Make coverage file
      run: npm run report-coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.0.0    