name: Redis tests

on:
  push:
    branches:
      - development

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Start redis
      uses: zhulik/redis-action@1.1.0
        
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: nyc npm run test
      env:
        CI: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.0.0    