name: Redis tests

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: APIs/__tests__
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Start redis
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: '7.0'
        
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
      env:
        CI: true